
// PURCHASE ORDER
export const GET_POS = 'GET_POS';
export const GET_REQ_ATT_DEPTS = 'GET_REQ_ATT_DEPTS';
export const GET_POS_BY_SEARCH = 'GET_POS_BY_SEARCH';
export const GET_PO = 'GET_PO';
export const CREATE_PO = 'CREATE_PO';
export const UPDATE_PO_BY_AM = 'UPDATE_PO_BY_AM';
export const UPDATE_PO_BY_AUTO = 'UPDATE_PO_BY_AUTO';
export const UPDATE_PO_BY_LOGISTICS = 'UPDATE_PO_BY_LOGISTICS';
export const UPDATE_CELL_EDIT_BY = 'UPDATE_CELL_EDIT_BY';

// BUYER
export const GET_BUYERS = 'GET_BUYERS';


// AUTH
export const AUTH_SIGNIN = 'AUTH_SIGNIN';
export const AUTH_CHANGE_PASSWORD = 'AUTH_CHANGE_PASSWORD';
export const START_LOADING = 'START_LOADING';
export const END_LOADING = 'END_LOADING';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

// STATUS
export const GET_STATUS = 'GET_STATUS';

// BUYER
export const GET_DEPARTMENTS = 'GET_DEPARTMENTS';

//ORDER ITEM
export const GET_ORDER_ITEMS_POID = 'GET_ORDER_ITEMS_POID';
export const GET_ORDER_ITEMS_IMAGES_POID = 'GET_ORDER_ITEMS_IMAGES_POID';
export const GET_ORDER_ITEM_IMAGE = 'GET_ORDER_ITEM_IMAGE';
export const CREATE_ORDER_ITEM_POID = 'CREATE_ORDER_ITEM_POID';
export const UPDATE_CELL_ORDER_ITEM = 'UPDATE_CELL_ORDER_ITEM';
export const UPDATE_CELL_ORDER_ITEM_IMAGE = 'UPDATE_CELL_ORDER_ITEM_IMAGE';
export const DELETE_ORDER_ITEM = 'DELETE_ORDER_ITEM';
export const GET_ORDER_ITEM_STATUS_OPEN = 'GET_ORDER_ITEM_STATUS_OPEN';
export const UPDATE_CELL_ORDER_ITEM_BULK = 'UPDATE_CELL_ORDER_ITEM_BULK';
export const CLEAR_DATE_CELL_ORDER_ITEM_BULK = 'CLEAR_DATE_CELL_ORDER_ITEM_BULK';
export const UPDATE_CELL_ORDER_ITEM_ITEM_CODE = 'UPDATE_CELL_ORDER_ITEM_ITEM_CODE'; 

//LOADING
export const START_LOADING_HOME = 'START_LOADING_HOME';
export const END_LOADING_HOME = 'END_LOADING_HOME';