

// BUYER
export const GET_BUYERS = 'GET_BUYERS';


// AUTH
export const AUTH_SIGNIN = 'AUTH_SIGNIN';
export const AUTH_CHANGE_PASSWORD = 'AUTH_CHANGE_PASSWORD';
export const START_LOADING = 'START_LOADING';
export const END_LOADING = 'END_LOADING';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

// MATERIAL
export const GET_MATERIALS = 'GET_MATERIALS';

// SUPPLIER
export const GET_SUPPLIERS = 'GET_SUPPLIERS';

// ITEM
export const CREATE_ITEM = 'CREATE_ITEM';
export const GET_ITEMS = 'GET_ITEMS'
export const EDIT_ITEM = 'EDIT_ITEM'

// MOLD
export const CREATE_MOLD = 'CREATE_MOLD';
export const GET_MOLDS_BY_ITEM_ID = 'GET_MOLDS_BY_ITEM_ID';
export const EDIT_MOLD_WITH_ID = 'EDIT_MOLD_WITH_ID';

// DELIVERY
export const ADD_DELIVERY = 'ADD_DELIVERY';
export const GET_DELIVERIES_BY_MOLD_ID = 'GET_DELIVERIES_BY_MOLD_ID';
export const EDIT_DELIVERY_WITH_ID = 'EDIT_DELIVERY_WITH_ID';
 

//LOADING
export const START_LOADING_HOME = 'START_LOADING_HOME';
export const END_LOADING_HOME = 'END_LOADING_HOME';